import 'package:flutter/material.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF040B16),
      body: SafeArea(
        child: Column(
          children: [
            _header(context),
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(24),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Privacy & Data Policy',
                      style: TextStyle(
                        fontSize: 24,
                        fontWeight: FontWeight.w800,
                        color: Colors.white,
                        letterSpacing: -0.5,
                      ),
                    ),
                    const SizedBox(height: 8),
                    const Text(
                      'Last updated: August 2026',
                      style: TextStyle(color: Color(0xFF64748B), fontSize: 13),
                    ),
                    const SizedBox(height: 24),
                    _sectionTitle('1. Data Localism'),
                    _sectionBody(
                      'FinPulse values your security and privacy. All transactions, financial accounts, budget targets, '
                      'and personalized insights generated by the AI model are stored and processed locally on your physical device. '
                      'We do not sell, rent, or distribute your personal financial history to third parties.',
                    ),
                    _sectionTitle('2. Synchronization & Cloud Storage'),
                    _sectionBody(
                      'If cloud backup or synchronization features are enabled, your encrypted transaction data is '
                      'safely sync\'d with our Firestore servers. This data is exclusively accessible by you via your validated '
                      'credentials. You can delete your cloud-stored databases at any time from the account management tab.',
                    ),
                    _sectionTitle('3. Live SMS Capture (Android)'),
                    _sectionBody(
                      'For live expense detection, FinPulse listens to incoming financial SMS notifications locally. '
                      'No text message payload or message body is uploaded or shared. The parsing mechanism happens fully '
                      'on-device, extracts only the transaction amounts and merchant names, and discards all other contents.',
                    ),
                    _sectionTitle('4. Biometric Information'),
                    _sectionBody(
                      'Biometric details (fingerprints, face data) configured for app lock are managed exclusively by the '
                      'underlying operating system. FinPulse cannot access, read, or store any biometric data; it merely '
                      'requests confirmation of identity from the system secure enclave.',
                    ),
                    _sectionTitle('5. Consent & Support'),
                    _sectionBody(
                      'By using FinPulse, you consent to this local-first policy. If you have any inquiries regarding data protection '
                      'or wish to purge your local databases, you can do so immediately under the Settings dashboard.',
                    ),
                    const SizedBox(height: 40),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _header(BuildContext context) => Padding(
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
        child: Row(
          children: [
            GestureDetector(
              onTap: () => Navigator.pop(context),
              child: Container(
                width: 36,
                height: 36,
                decoration: BoxDecoration(
                  color: const Color(0xFF0D1117),
                  shape: BoxShape.circle,
                  border: Border.all(color: Colors.white.withOpacity(0.08)),
                ),
                child: const Icon(Icons.arrow_back_ios_new_rounded, color: Colors.white, size: 16),
              ),
            ),
            const Expanded(
              child: Center(
                child: Text(
                  'Privacy Policy',
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.w700, color: Colors.white),
                ),
              ),
            ),
            const SizedBox(width: 36),
          ],
        ),
      );

  Widget _sectionTitle(String title) => Padding(
        padding: const EdgeInsets.only(top: 24, bottom: 8),
        child: Text(
          title,
          style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w700, color: Colors.white),
        ),
      );

  Widget _sectionBody(String body) => Text(
        body,
        style: const TextStyle(fontSize: 14, color: Color(0xFF94A3B8), height: 1.6),
      );
}
